[images]
  remote_images = ["https://github.com/*/*/", "https://avatars.githubusercontent.com/*"]

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  NEXT_PUBLIC_GITHUB_USERNAME = "imkenough"
  NEXT_PUBLIC_GITHUB_TOKEN = "@github_token"

[context.deploy-preview.environment]
  NEXT_PUBLIC_GITHUB_USERNAME = "imkenough"
  NEXT_PUBLIC_GITHUB_TOKEN = "@github_token"